# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fricandó Rostisseria
email: hola@fricandorostisseria.com
description: >- # this means to ignore newlines until "baseurl:"
  Comida casera para llevar. Tu tienda de platos cocinados en Lloreda,
  Badalona (Barcelona).
  Tel. 670 298 42 / 93 399 44 24.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fricandorostisseria.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username: jekyll
# locale: es_ES

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  comidas:
    output: true
    permalink: /comidas/:path/
  cenas:
    output: true
    permalink: /cenas/:path/
  bebidas:
    output: true
    permalink: /bebidas/:path/
  encargos:
    output: true
    permalink: /encargos/:path/
